---
driver:
  name: ec2
  require_chef_omnibus: <%= ENV['REQUIRE_CHEF_OMNIBUS'] %>
  tags: {
    "Name": <%= ENV['COOKBOOK'] %>
  }
  aws_ssh_key_id: <%= ENV['EC2_SSH_KEY_ID'] %>
  region: <%= ENV['EC2_REGION'] %>
  availability_zone: <%= ENV['EC2_AZ'] %>
  subnet_id: <%= ENV['EC2_SUBNET_ID'] %>
  instance_type: <%= ENV['EC2_INSTANCE_TYPE'] %>
  image_search:
    "name": <%= ENV['EC2_IMAGE_NAME'] %>
  security_group_ids: [<%= ENV['EC2_SG'] %>]
  retryable_tries: 120

provisioner:
  name: chef_zero

transport:
  name: winrm
  username: <%= ENV['WIN_USER'] %>
  password: <%= ENV['WIN_PASS'] %>

platforms:
  - name: windows

suites:
  - name: <%= ENV['COOKBOOK'] %>
    data_bags_path: <%= ENV['CHEF_DATA_BAGS'] %>
    encrypted_data_bag_secret_key_path: <%= ENV['CHEF_SECRET_FILE'] %>
    run_list:
      - recipe[<%= ENV['COOKBOOK'] %>::default]
      - recipe[minitest-handler]
    attributes:
      daptiv_site:
        version: <%= ENV['LATEST_PPM_PACKAGE'] %>
