source 'https://rubygems.org'

gem 'chefspec', '~> 4.1'
gem 'rspec', '~> 3.1.0'
gem 'rspec-core', '~> 3.1.7'
gem 'rspec-expectations', '~> 3.1.2'
gem 'rspec-mocks', '~> 3.1.3'
gem 'chef', '~> 11.14'
gem 'foodcritic', '~> 3.0.0'
gem 'daptiv-foodcritic-rules', '~> 0.0.2'
gem 'tailor'
gem 'log_switch', '~> 0.4.0'
gem 'rake'
gem 'berkshelf', '~> 4.0'
gem 'minitest-chef-handler'
