source 'https://rubygems.org'

gem 'chef', '~> 11.4.0'
gem 'foodcritic', '~> 3.0.0'
gem 'daptiv-foodcritic-rules'
gem 'tailor', '~> 1.3.1'
gem 'rake'
gem 'berkshelf', '~> 2.0'
gem 'minitest-chef-handler'
gem 'daptiv-chef-ci', '~> 0.0.14'
